# Generated by Django 4.1.6 on 2023-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_optioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioninfo',
            name='downfactor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='optioninfo',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='optioninfo',
            name='timeperiod',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='optioninfo',
            name='upfactor',
            field=models.FloatField(),
        ),
    ]
