# Generated by Django 4.1.6 on 2023-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_optioninfo_downfactor_alter_optioninfo_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioninfo',
            name='timeperiod',
            field=models.IntegerField(null=True),
        ),
    ]
